### ISSUE TITLE
No wildcard selection possible in query_assets() of AssetManager

### ISSUE THREAD

**Issue by mhorst00** [boschresearch/assets2036py#3]
Currently, it is not possible to use wildcard selectors while querying for assets with the manager. 
This is the error I get while trying to use wildcard querying with '+' as a selector.

> `Traceback (most recent call last):
>   File "/home/mhorst/workspace/arena2036-equipment/app.py", line 65, in <module>
>     eps = get_endpoints(mgr)
>   File "/home/mhorst/workspace/arena2036-equipment/app.py", line 31, in get_endpoints
>     endpoints = mgr.query_assets("+", "+")
>   File "/home/mhorst/workspace/arena2036-equipment/.venv/lib64/python3.10/site-packages/assets2036py/assetmanager.py", line 200, in query_assets
>     return self.client.query_asset_names(namespace, *submodel_names)
>   File "/home/mhorst/workspace/arena2036-equipment/.venv/lib64/python3.10/site-packages/assets2036py/communication.py", line 192, in query_asset_names
>     re.search(f"{namespace}/([A-Za-z0-9._-]*)/{sm}/_meta", topic)[1])
>   File "/usr/lib64/python3.10/re.py", line 200, in search
>     return _compile(pattern, flags).search(string)
>   File "/usr/lib64/python3.10/re.py", line 303, in _compile
>     p = sre_compile.compile(pattern, flags)
>   File "/usr/lib64/python3.10/sre_compile.py", line 764, in compile
>     p = sre_parse.parse(p, flags)
>   File "/usr/lib64/python3.10/sre_parse.py", line 948, in parse
>     p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
>   File "/usr/lib64/python3.10/sre_parse.py", line 443, in _parse_sub
>     itemsappend(_parse(source, state, verbose, nested + 1,
>   File "/usr/lib64/python3.10/sre_parse.py", line 668, in _parse
>     raise source.error("nothing to repeat",
> re.error: nothing to repeat at position 0`
>

**Comment by mhorst00** [comment]
This is the call used to produce the error:
`mgr.query_assets("+","+")`

**Comment by DaEwe** [comment]
Fixed in 9e72dafb686757c3df45b02f869e1573fc3e6d77
