### ISSUE TITLE
Disable/remove debug logging in communication.py

### ISSUE THREAD

**Issue by FlorianFritz** [boschresearch/assets2036py#4]
The statement [`logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)`](https://github.com/boschresearch/assets2036py/blob/77449f0e1a3b5b853a9a5d067f2ebbb216b9cf5b/assets2036py/communication.py#L35) on line 35 of communication.py overwrites application wide logging levels. Please remove this line from the code. 

One should set the logging level in the application using this library not in the library itself.

Best regards from the DFA project.

**Comment by DaEwe** [comment]
You are absolutely right. Fix is under way!
