### ISSUE TITLE
Update pypi package

### ISSUE THREAD

**Issue by FlorianFritz** [boschresearch/assets2036py#7]
The pypi package is still at version 0.0.13 (see https://pypi.org/project/assets2036py/) which does not reflect code changes since https://github.com/boschresearch/assets2036py/commit/8a697e535008a49bda39899d32b3f9bfa5af0de3 on March 14th, like resolved issue #4.

**Comment by DaEwe** [comment]
fixed in https://github.com/boschresearch/assets2036py/commit/5828680eeca85fab82f2132eb502c864327e7e8d.
Thanks!
